export const iconNames = [
	'activity',
	'arrow-down',
	'arrow-left',
	'arrow-right',
	'arrow-up',
	'at-sign',
	'bar-chart-3',
	'bell',
	'book-open',
	'bookmark',
	'calendar',
	'check',
	'chevron-down',
	'chevron-left',
	'chevron-right',
	'chevron-up',
	'chevrons-up-down',
	'circle-alert',
	'circle-check',
	'circle-help',
	'circle',
	'clock',
	'code',
	'command',
	'copy',
	'corner-down-left',
	'download',
	'external-link',
	'eye-off',
	'eye',
	'file-text',
	'file',
	'filter',
	'folder-plus',
	'folder',
	'git-branch',
	'git-pull-request',
	'hash',
	'heart',
	'home',
	'image',
	'inbox',
	'info',
	'link',
	'lock',
	'message-circle',
	'message-square',
	'minus',
	'moon',
	'more-horizontal',
	'more-vertical',
	'panel-left',
	'panel-right',
	'paperclip',
	'pause',
	'pencil',
	'pie-chart',
	'play',
	'plus',
	'refresh-ccw',
	'search',
	'send-horizontal',
	'settings',
	'share-2',
	'slash',
	'sliders-horizontal',
	'smile',
	'sparkles',
	'square',
	'star',
	'sun',
	'tag',
	'terminal',
	'thumbs-down',
	'thumbs-up',
	'trash-2',
	'triangle-alert',
	'unlock',
	'upload',
	'user',
	'users',
	'x',
	'zap'
] as const

export const brandAssetNames = [
	'logo-black',
	'logo-mark',
	'logo-white',
	'wordmark',
	'wordmark-black'
] as const

export type BrandAssetName = (typeof brandAssetNames)[number]
export type IconName = (typeof iconNames)[number]

export function getIconAssetPath(iconName: IconName): string {
	return `assets/icons/${iconName}.svg`
}

export function getBrandAssetPath(assetName: BrandAssetName): string {
	return `assets/brand/${assetName}.svg`
}
