const concreteClassNameKeyGroups = [
	`
avatar avatarLarge avatarSmall badge badgeCount badgeError badgeGhost badgeSolid
badgeTerminal badgeUltra brandMark button buttonDanger buttonGhost
buttonIcon buttonKbd buttonLarge buttonPrimary buttonSecondary buttonShortcut buttonSky buttonSkySoft
buttonSmall buttonSoft buttonTiny buttonUltra calendarDays calendarGrid calendarWeekdays card
cardBody cardInteractive cardRaised cardSunken cardTitle caret caretDown caretLarge
caretOpen caretSmall caretUp chartArea chartAxis chartAxisLabel chartBar chartBarComparison
chartBarTrack chartBaseline chartEndLabel chartEndpoint chartFrame chartGrid chartLine
chartMessage chartPlotBackground chartPoint chartRowLabel chartStackSegment chartSvg chartTarget
`,
	`
chartTickLabel chartValueLabel checkbox checkboxChecked checkRow chip chipSelected cluster code
codeBody codeCopy codeGutter codeHead codeLang codeLine codePre commandAside controlGroup
commandBody commandCopy commandEmpty commandFooter commandGroup commandGroupTitle commandIcon commandItem
commandMenu commandSearch composerSurface tokenRail composerToken composerMenuLayer composerToolbar conceptConnector conceptConnectorMuted
conceptConnectorSelected conceptFrame conceptFrameLarge conceptFrameMuted conceptFrameSelected conceptFrameSmall dataSurface dataSurfaceActions dataSurfaceFooter dataSurfaceHeader dataSurfaceHeaderBody dataSurfaceMeta pagination table
tableAlignCenter tableAlignRight tableEmpty tableEmptyCell tableFrozen tableSelectionCell tableSort tableViewport dataToneError
dataToneMuted dataToneSky dataToneTerminal dataToneUltra datePicker delta deltaBasis deltaIcon
`,
	`
deltaLarge deltaNegative deltaNeutral deltaPositive deltaSmall deltaWash deltaXlarge diagramCanvasCard
diagramCanvasControls diagramCanvasEdge diagramCanvasEdgeDashed diagramCanvasEdgeDotted diagramCanvasEdgeReference diagramCanvasEdgeSelected diagramCanvasEdgeStep diagramCanvasEdges
diagramCanvasElement diagramCanvasFooter diagramCanvasHeader diagramCanvasItemButton diagramCanvasLegend diagramCanvasLegendCompute diagramCanvasLegendData diagramCanvasLegendEvent
diagramCanvasLegendFlow diagramCanvasLegendReference diagramCanvasMinimap diagramCanvasMinimapNode diagramCanvasMinimapSelected diagramCanvasPanning diagramCanvasRail diagramCanvasRailActive
diagramCanvasStage diagramCanvasStatus diagramCanvasTitleBlock diagramCanvasToneError diagramCanvasToneInk diagramCanvasToneSky diagramCanvasToneTerminal diagramCanvasToneUltra
diagramCanvasViewport diagramItem diagramItemChart diagramItemCode diagramItemDocument diagramItemKind diagramItemMeta diagramItemMetric
diagramItemMuted diagramItemSelected diagramItemStatus diagramItemTable diagramNode diagramNodeIcon diagramNodeMuted diagramNodeSelected
diagramNodeText diagramRoleBoundary diagramRoleCompute diagramRoleData diagramRoleDecision diagramRoleError diagramRoleExternal diagramToneError
`,
	`
diagramToneInk diagramToneSky diagramToneTerminal diagramToneUltra distribution distributionRow distributionValue divider dock
donutCenter donutCenterLabel donutCenterValue donutChart donutSegment donutTrack dots dropzone dropzoneAction dropzoneDescription dropzoneIcon
dropzoneTitle composerEditor emptyBody emptyState emptyStateLarge emptyStateSky emptyStateSmall
emptyTitle field fileInput fileUpload fileUploadAction flowDiagramCanvas flowDiagramCard flowDiagramControls
flowDiagramEdge flowDiagramEdgeDashed flowDiagramEdgeDotted flowDiagramEdgePulse flowDiagramEdgeSelected flowDiagramGrid flowDiagramNode flowDiagramNodeAccent
flowDiagramNodeInverse flowDiagramNodeSelected flowDiagramNodeSubtitle flowDiagramNodeTitle flowDiagramViewport focusTarget composerFooter formControl
formControlIconButton formControlWrap formField formFieldCount formFieldDescription
formFieldFoot formFieldHead formFieldLabel formFieldMessage formFieldMeta
`,
	`
frame frameBody frameEyebrow frameFoot frameHead frameMeta header headerActions headerContent
headerMeta heading heatmapCell heatmapCellValue grid heatmapChart heatmapColumnLabel heatmapRowLabel help helpError horizontalBarRow horizontalBars icon iconButton imageUpload indicator
indicatorDot indicatorError indicatorMuted indicatorSky indicatorTerminal indicatorUltra inlineCode input inputError inputHasIcon inputIcon inputWrap
kbd kbdDark label labelError labelInk labelSky labelSunken labelTerminal inline
labelUltra lattice legend legendValue lines link linkExternal linkMuted linkNav linkSky
mark `,
	`
message messageActions messageAvatar messageBubble messageBubbleOutbound messageMeta messagePlain messageStack stepper
optionRow optionRowAside panel panelBody panelFooter
optionRowCopy optionRowIcon
pill progressError progressFill progressLined progressRing progressRingCenter progressRingFill progressRingTrack
progressRingUnit progressShuttle progressSky progressTerminal progressThick progressThin progressTrack progressUltra
radio radioChecked radioDot rail tokenRailItem range rangeTrack rangeValues root row rowIcon rowInteractive
rowLabel rowMeta
`,
	`
section sectionBody segmentedProgress select selectWrap composerSendButton skeleton slider
scrollArea sliderSky sparkline sparklineArea sparklineBar sparklineDot sparklineEndpoint sparklineError sparklineLine
sparklineNeutral sparklineTerminal spinner spinnerInverse spinnerSky spinnerSvg stackedBarGroup stackedBars
stat statDisplay statLabel statLarge statMeta statMuted statNumber statSky
split splitAside splitBody stack statSmall statUnit statValue statXlarge statXsmall composerSubmitDock surface switch switchChecked
switchTrack syntaxAttribute syntaxComment syntaxFunction syntaxIdentifier syntaxKeyword syntaxNumber syntaxOperator
syntaxPunctuation syntaxString syntaxType tag tagActive tagClose tagError tagLarge text
tagOutline tagSelected tagSky tagSmall tagTerminal tagUltra textarea timeMenu
trace traceStatus traceSteps traceSummaryMain traceSummaryText
`,
	`
timePicker toolButton toolbar toolbarCompact toolbarDivider toolbarGroup toolbarRoot toolbarRootButton
toolbarRootButtonKbd toolbarRootButtonLabel toolbarRootGroup toolbarRootSeparator toolCall toolCallBody toolCallStatus toolCodeBlock
toolItalic toolOutput toolStrike tooltip tooltipAnchor tooltipBottom tooltipBubble tooltipForceOpen
tooltipKbd tooltipLeft tooltipRich tooltipRight tooltipTop tooltipWrap toolUnderline uploadCopy
uploadItem uploadList uploadProgress uploadRemove uploadThumb validationList visuallyHidden wordmark
alert alertAction alertBody alertIcon dialogSurface disclosurePanel disclosurePanelBody
disclosurePanelSummary drawerSurface fieldRow fieldRowControl fieldRowCopy fieldRowDescription fieldRowLabel
fieldRowMeta listbox listboxEmpty listboxItems menuGroup menuGroupItems menuGroupTitle menuSurface
overlay pickerButton pickerButtonLabel pickerSurface searchInputControl searchInputIcon searchInputRoot
searchInputShortcut searchInputShortcutKey token tokenLabel tokenRemove validationListCopy validationListIcon validationListItem
`
] as const

export type ConcreteClassName = string

type ConcreteClassNameMap = Readonly<Record<ConcreteClassName, string>>

const concreteClassNameGroups: readonly string[] = concreteClassNameKeyGroups

export const concreteClassNameEntries: readonly (readonly [string, string])[] =
	concreteClassNameGroups.flatMap(group =>
		splitConcreteClassNameKeys(group).map(key => [key, getConcreteClassName(key)] as const)
	)

export const concreteClassNames: ConcreteClassNameMap = Object.fromEntries(
	concreteClassNameEntries
) as ConcreteClassNameMap

function splitConcreteClassNameKeys(group: string): readonly string[] {
	return group.trim().split(/\s+/u)
}

export function getConcreteClassName(key: string): string {
	return `concrete-${toKebabCase(key)}`
}

function toKebabCase(value: string): string {
	return value.replace(/[A-Z]/gu, character => `-${character.toLowerCase()}`)
}
