const concreteClassNameKeyGroups = [
	`
avatar avatarLarge avatarSmall badge badgeCount badgeError badgeGhost badgeSolid
badgeTerminal badgeUltra brandMark bubble bubbleOutbound button buttonDanger buttonGhost
buttonIcon buttonKbd buttonLarge buttonPrimary buttonSecondary buttonShortcut buttonSky buttonSkySoft
buttonSmall buttonSoft buttonTiny buttonUltra calendarGrid calendarPanel calendarWeekdays card
cardBody cardInteractive cardRaised cardSunken cardTitle caret caretDown caretLarge
caretOpen caretSmall caretUp chartArea chartAxis chartAxisLabel chartBar chartBarComparison
chartBarTrack chartBaseline chartCard chartEndLabel chartEndpoint chartGrid chartLegend chartLine
chartMessage chartPlotBackground chartPoint chartRowLabel chartStackSegment chartSurface chartSvg chartTarget
`,
	`
chartTickLabel chartValueLabel checkbox checkboxChecked checkRow chip chipSelected code
codeBody codeCopy codeGutter codeHead codeLang codeLine codePre commandAside
commandBody commandCopy commandEmpty commandFooter commandGroup commandGroupTitle commandIcon commandItem
commandMenu commandSearch composer composerRail composerToken composerToolbar conceptConnector conceptConnectorMuted
conceptConnectorSelected conceptFrame conceptFrameLarge conceptFrameMuted conceptFrameSelected conceptFrameSmall dataCardHeader dataTable
dataTableAction dataTableAlignCenter dataTableAlignRight dataTableCard dataTableEmpty dataTableEmptyCell dataTableFilter dataTableFrozen
dataTableHeader dataTablePagination dataTableScroll dataTableSearch dataTableSelectionCell dataTableSort dataTableToolbar dataToneError
dataToneMuted dataToneSky dataToneTerminal dataToneUltra datePicker delta deltaBasis deltaIcon
`,
	`
deltaLarge deltaNegative deltaNeutral deltaPositive deltaSmall deltaWash deltaXlarge diagramCanvasCard
diagramCanvasControls diagramCanvasEdge diagramCanvasEdgeDashed diagramCanvasEdgeDotted diagramCanvasEdgeReference diagramCanvasEdgeSelected diagramCanvasEdgeStep diagramCanvasEdges
diagramCanvasElement diagramCanvasFooter diagramCanvasHeader diagramCanvasItemButton diagramCanvasLegend diagramCanvasLegendCompute diagramCanvasLegendData diagramCanvasLegendEvent
diagramCanvasLegendFlow diagramCanvasLegendReference diagramCanvasMinimap diagramCanvasMinimapNode diagramCanvasMinimapSelected diagramCanvasPanning diagramCanvasRail diagramCanvasRailActive
diagramCanvasStage diagramCanvasStatus diagramCanvasTitleBlock diagramCanvasToneError diagramCanvasToneInk diagramCanvasToneSky diagramCanvasToneTerminal diagramCanvasToneUltra
diagramCanvasViewport diagramItem diagramItemChart diagramItemCode diagramItemDocument diagramItemKind diagramItemMeta diagramItemMetric
diagramItemMuted diagramItemSelected diagramItemStatus diagramItemTable diagramNode diagramNodeIcon diagramNodeMuted diagramNodeSelected
diagramNodeText diagramRoleBoundary diagramRoleCompute diagramRoleData diagramRoleDecision diagramRoleError diagramRoleExternal diagramToneError
`,
	`
diagramToneInk diagramToneSky diagramToneTerminal diagramToneUltra distribution distributionRow distributionValue divider
donutCenter donutChart donutSegment donutTrack dots dropzone dropzoneDescription dropzoneIcon
dropzoneTitle editor emptyBody emptyMenu emptyState emptyStateLarge emptyStateSky emptyStateSmall
emptyTitle field fileInput fileUpload fileUploadAction flowDiagramCanvas flowDiagramCard flowDiagramControls
flowDiagramEdge flowDiagramEdgeDashed flowDiagramEdgeDotted flowDiagramEdgePulse flowDiagramEdgeSelected flowDiagramGrid flowDiagramNode flowDiagramNodeAccent
flowDiagramNodeInverse flowDiagramNodeSelected flowDiagramNodeSubtitle flowDiagramNodeTitle flowDiagramViewport focusTarget footer formControl
formControlIconButton formControlWrap formDialog formDrawer formEyebrow formField formFieldCount formFieldDescription
formFieldFoot formFieldHead formFieldLabel formFieldMessage formFieldMeta formGrid formOverlay formRow
`,
	`
formRowControl formRowCopy formRowDescription formRowLabel formRowMeta formSection formSectionAction formSectionBody
formSectionHeader formShell formShellActions formShellBody formShellFooter formShellHeader formShellIntro formShellMeta
formShellTitleRow frame frameBody frameEyebrow frameFoot frameHead frameMeta heatmapCell
heatmapChart help helpError horizontalBarRow horizontalBars icon imageUpload indicator
indicatorDot indicatorMuted inlineCode input inputError inputHasIcon inputIcon inputWrap
kbd kbdDark label labelError labelInk labelSky labelSunken labelTerminal
labelUltra lattice lines link linkExternal linkMuted linkNav linkSky
mark menu menuCopy menuItem menuLayer menuList menuMeta menuTitle
`,
	`
message messageActions messageAvatar messageBubble messageMeta messagePlain messageStack meterCard
meterFooter meterHeader meterRingCard metricCard metricCardCompact metricDescription metricHeader metricLabel
metricSparkline multiSelect multiSelectControl multiSelectMenu multiSelectToggle multiSelectValues numberStepper pickerControl
pill progressError progressFill progressLined progressRing progressRingCenter progressRingFill progressRingTrack
progressRingUnit progressShuttle progressSky progressTerminal progressThick progressThin progressTrack progressUltra
radio radioChecked radioDot railChip rangeSlider rangeSliderTrack rangeSliderValues reasoning
reasoningStatus reasoningSteps reasoningSummaryMain reasoningSummaryText root row rowIcon rowInteractive
rowLabel rowMeta searchBar searchInput searchLeading searchMenu searchShell searchShortcut
`,
	`
searchShortcutKey searchToken segmentedProgress select selectWrap sendButton skeleton slider
sliderSky sparkline sparklineArea sparklineBar sparklineDot sparklineEndpoint sparklineError sparklineLine
sparklineNeutral sparklineTerminal spinner spinnerInverse spinnerSky spinnerSvg stackedBarGroup stackedBars
stat statDisplay statLabel statLarge statMeta statMuted statNumber statSky
statSmall statUnit statValue statXlarge statXsmall submitDock switch switchChecked
switchTrack syntaxAttribute syntaxComment syntaxFunction syntaxIdentifier syntaxKeyword syntaxNumber syntaxOperator
syntaxPunctuation syntaxString syntaxType tag tagActive tagClose tagError tagLarge
tagOutline tagSelected tagSky tagSmall tagTerminal tagUltra textarea timeMenu
`,
	`
timePicker toolButton toolbar toolbarCompact toolbarDivider toolbarGroup toolbarRoot toolbarRootButton
toolbarRootButtonKbd toolbarRootButtonLabel toolbarRootGroup toolbarRootSeparator toolCall toolCallBody toolCallStatus toolCodeBlock
toolItalic toolOutput toolStrike tooltip tooltipAnchor tooltipBottom tooltipBubble tooltipForceOpen
tooltipKbd tooltipLeft tooltipRich tooltipRight tooltipTop tooltipWrap toolUnderline uploadCopy
uploadItem uploadList uploadProgress uploadRemove uploadThumb validationList validationSummary validationSummaryAction
validationSummaryBody validationSummaryHead validationSummaryIcon visuallyHidden wordmark
`
] as const

export type ConcreteClassName = string

type ConcreteClassNameMap = Readonly<Record<ConcreteClassName, string>>

const concreteClassNameGroups: readonly string[] = concreteClassNameKeyGroups

export const concreteClassNameEntries: readonly (readonly [string, string])[] =
	concreteClassNameGroups.flatMap(group =>
		splitConcreteClassNameKeys(group).map(key => [key, getConcreteClassName(key)] as const)
	)

export const concreteClassNames: ConcreteClassNameMap = Object.fromEntries(
	concreteClassNameEntries
) as ConcreteClassNameMap

function splitConcreteClassNameKeys(group: string): readonly string[] {
	return group.trim().split(/\s+/u)
}

export function getConcreteClassName(key: string): string {
	return `concrete-${toKebabCase(key)}`
}

function toKebabCase(value: string): string {
	return value.replace(/[A-Z]/gu, character => `-${character.toLowerCase()}`)
}
